### ISSUE TITLE
LockingFailureException in GormTokenStoreService

### ISSUE THREAD

**Issue by xorkk** [bluesliverx/grails-spring-security-oauth2-provider#108]
17:52:28,201 ERROR [StackTrace](http-/0:0:0:0:0:0:0:0:8090-2) Full Stack Trace:: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [AccessToken#100071]
    at org.hibernate.persister.entity.AbstractEntityPersister.check(AbstractEntityPersister.java:2541) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3403) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3630) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:114) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:349) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:67) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1191) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1675) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:402) [hibernate-core-4.3.5.Final.jar:4.3.5.Final]
    at org.codehaus.groovy.grails.orm.hibernate.HibernateGormStaticApi$_findWhere_closure3.doCall(HibernateGormStaticApi.groovy:449) [grails-datastore-gorm-hibernate4-3.1.2.RELEASE.jar:]
    at sun.reflect.GeneratedMethodAccessor227.invoke(Unknown Source) [:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_79]
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-all-2.3.6.jar:2.3.6]
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-all-2.3.6.jar:2.3.6]
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207) [groovy-all-2.3.6.jar:2.3.6]
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110) [groovy-all-2.3.6.jar:2.3.6]
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) [groovy-all-2.3.6.jar:2.3.6]
    at groovy.lang.Closure.call(Closure.java:423) [groovy-all-2.3.6.jar:2.3.6]
    at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:51) [groovy-all-2.3.6.jar:2.3.6]
    at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:81) [groovy-all-2.3.6.jar:2.3.6]
    at com.sun.proxy.$Proxy59.doInHibernate(Unknown Source)
    at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:179) [grails-datastore-gorm-hibernate4-3.1.2.RELEASE.jar:]
    at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:123) [grails-datastore-gorm-hibernate4-3.1.2.RELEASE.jar:]
    at org.codehaus.groovy.grails.orm.hibernate.HibernateGormStaticApi.findWhere(HibernateGormStaticApi.groovy:437) [grails-datastore-gorm-hibernate4-3.1.2.RELEASE.jar:]
    at org.grails.datastore.gorm.GormStaticApi.findWhere(GormStaticApi.groovy:621) [grails-datastore-gorm-3.1.2.RELEASE.jar:]
    at AccessToken.findWhere(AccessToken.groovy) [classes:]
    at AccessToken$findWhere.call(Unknown Source)
    at grails.plugin.springsecurity.oauthprovider.GormTokenStoreService.storeAccessToken(GormTokenStoreService.groovy:75) [classes:]
    at grails.plugin.springsecurity.oauthprovider.GormTokenStoreService$$FastClassBySpringCGLIB$$adfe37ea.invoke(<generated>) [spring-core-4.0.6.RELEASE.jar:]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at grails.plugin.springsecurity.oauthprovider.GormTokenStoreService$$EnhancerBySpringCGLIB$$733e5b7f.storeAccessToken(<generated>) [spring-core-4.0.6.RELEASE.jar:]
    at org.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:122) [spring-security-oauth2-2.0.7.RELEASE.jar:]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_79]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at com.sun.proxy.$Proxy46.createAccessToken(Unknown Source)
    at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:70) [spring-security-oauth2-2.0.7.RELEASE.jar:]
    at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:65) [spring-security-oauth2-2.0.7.RELEASE.jar:]
    at org.springframework.security.oauth2.provider.client.ClientCredentialsTokenGranter.grant(ClientCredentialsTokenGranter.java:47) [spring-security-oauth2-2.0.7.RELEASE.jar:]
    at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38) [spring-security-oauth2-2.0.7.RELEASE.jar:]
    at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:132) [spring-security-oauth2-2.0.7.RELEASE.jar:]
    at grails.plugin.springsecurity.oauthprovider.endpoint.WrappedTokenEndpoint.postAccessToken(WrappedTokenEndpoint.java:22) [classes:]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_79]
    at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) [spring-web-4.0.6.RELEASE.jar:4.0.6.RELEASE]

Step to reproduce: 
I use 3 "Advanced Rest Client" tab under chrome to call quickly /oauth/token (post)
parameters: grant_type: client_credentials, client_id: myClientID, client_secret: myClientSecret

2 of the 3 tabs returns a status 200 Success, but one returns a 500 Internal Server Error.

I think there is a transactional issue

thanks in advance

**Comment by bobby-vandiver** [comment]
Can you provide more information about your setup? What plugins are you using? What version of the OAuth2 plugin? What version of Grails? If you could provide a sample app demonstrating this problem, that would be great.

**Comment by xorkk** [comment]
It's difficult to me to create a sample app because it need a database...
So there is nothing special, 
Grails 2.4.3, plugins:  
        compile ":spring-security-oauth2-provider:2.0-RC5"
        compile ":spring-security-core:2.0-RC5"
        compile ":marshallers:0.6"
        compile ":rest-client-builder:2.1.0"

       runtime ":hibernate4:4.3.5.5" 
        runtime ":database-migration:1.4.0"
        runtime ':cors:1.1.6', {
            excludes 'spring-security-core', 'spring-security-web'
        }

thanks

**Comment by bobby-vandiver** [comment]
The `StaleObjectStateException` is caused when doing concurrent edits of an object while using optimistic locking. The domain classes generated by the plugin's `s2-init-oauth2-provider' script has this disabled by default.

What does your access token domain class look like, specifically the `version` field of the class's `mapping` field?

Also, what's your use case for requesting an `access_token` for the same client in rapid succession? Since you mentioned jmeter, is this something you're only seeing when doing load testing of your app?

**Comment by xorkk** [comment]
Ok thanks,
i removed the the line "version false" from the access token domain class.
But now when i try the same, i got this error:

ORA-00060: détection d'interblocage pendant l'attente d'une ressource
. Stacktrace follows:
Message: Heuristic completion: outcome state is mixed; nested exception is org.springframework.dao.CannotAcquireLockException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement
    Line | Method
->>   20 | getAccessToken in grails.plugin.springsecurity.oauthprovider.endpoint.WrappedTokenEndpoint
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    177 | doFilter       in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter       in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     82 | doFilter . . . in com.brandseye.cors.CorsFilter
|   1145 | runWorker      in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run            in java.lang.Thread

Caused by CannotAcquireLockException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement
->>   20 | getAccessToken in grails.plugin.springsecurity.oauthprovider.endpoint.WrappedTokenEndpoint
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    177 | doFilter       in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter       in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     82 | doFilter . . . in com.brandseye.cors.CorsFilter
|   1145 | runWorker      in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run            in java.lang.Thread

Caused by LockAcquisitionException: could not execute statement
->>   20 | getAccessToken in grails.plugin.springsecurity.oauthprovider.endpoint.WrappedTokenEndpoint
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    177 | doFilter       in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter       in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     82 | doFilter . . . in com.brandseye.cors.CorsFilter
|   1145 | runWorker      in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run            in java.lang.Thread

**Comment by bluesliverx** [comment]
@xorkk did you ever figure this out?

**Comment by bluesliverx** [comment]
Due to no feedback, I'm closing this issue. If it is still a problem, please open a new issue in the new project at https://github.com/grails-plugins/grails-spring-security-oauth2-provider.
