### ISSUE TITLE
Cannot set unlimited refresh tokens in 2.0-RC3

### ISSUE THREAD

**Issue by zgarbowitz** [bluesliverx/grails-spring-security-oauth2-provider#75]
Hi,

We just upgraded to 2.0-RC3, which includes Spring Security OAuth 2.0.6.RELEASE. According to springs release notes http://spring.io/blog/2015/02/02/spring-security-oauth-2-0-6-release-available-now, the new version should support refresh tokens that never expire by setting refreshTokenValiditySeconds to 0 in the client.

However, I just tried that. When I hit /oauth/token to refresh a token, I get the following error:

2015-03-25 13:11:06,700 ERROR [http-bio-8443-exec-10] org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver      - IllegalArgumentException occurred when processing request: [POST] /oauth/token - parameters:
scope: sdk
grant_type: refresh_token
refresh_token: ba17beca-ee34-484c-bd74-37f8eacbe8eb
Refresh token must be capable of expiring. Stacktrace follows:
java.lang.IllegalArgumentException: Refresh token must be capable of expiring
	at grails.plugin.springsecurity.oauthprovider.GormTokenStoreService.storeRefreshToken(GormTokenStoreService.groovy:112)
	at grails.plugin.springsecurity.oauthprovider.endpoint.WrappedTokenEndpoint.getAccessToken(WrappedTokenEndpoint.java:25)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:177)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

It's easy enough as a work-around to continue setting a very large refresh token expire time, but I wanted to point this out.

Thanks,
Zack

**Comment by bluesliverx** [comment]
Looks like this should be an easy fix, and for now you could workaround by overriding the tokenStore with a variant that supports non-expiring refresh tokens.

**Comment by bobby-vandiver** [comment]
This is working as intended. There are a few other features that have been added to the underlying Spring OAuth library that we don't currently expose via the plugin. My preference would be to add a configuration flag to the plugin to control whether refresh tokens can expire rather than use a magic value to indicate it.

**Comment by bobby-vandiver** [comment]
This is supported in the latest `2.0-SNAPSHOT`. Closing this issue.
