### ISSUE TITLE
Basic authentification not longer works

### ISSUE THREAD

**Issue by moniman** [bluesliverx/grails-spring-security-oauth2-provider#79]
Hi, 

Since I use 2.0-SNAPSHOT, the basic authentification (login/password) with spring security no longer works (facebook authentification too). 

The code is executed and the user is found. 
But after MyUserDetailsService.loadUserByUsername(String username) returne a new MyUserDetails(), nothing happend and I not connected.

And my conf is :

	compile ':spring-security-core:2.0-RC4'
	compile ':spring-security-facebook:0.17'
	compile ':spring-security-oauth2-provider:2.0-SNAPSHOT'

	grails {
	    plugin {
		// Spring Security Core plugin
		springsecurity {
		    userLookup.userDomainClassName = 'user.User'
		    userLookup.authorityJoinClassName = 'user.UserRole'
		    authority.className = 'user.Role'
		    password.algorithm = 'bcrypt'
		    successHandler.alwaysUseDefaultTargetUrl = false
		    successHandler.useReferer = true
		    logout.postOnly = false
		    logout.redirectToReferer = true
		    auth.loginFormUrl = '/login'
		    //useSecurityEventListener = true
		    useSwitchUserFilter = true
		    controllerAnnotations.staticRules = [
		        '/admin/**':                      ['ROLE_ADMIN'],
		        '/j_spring_security_exit_user':   ['permitAll'],
		        '/login/**':                      ['permitAll'],
		        '/logout/**':                     ['permitAll'],
		        '/**/js/**':                      ['permitAll'],
		        '/**/css/**':                     ['permitAll'],
		        '/**/images/**':                  ['permitAll'],
		        '/**/favicon.ico':                ['permitAll'],
		        '/index':                         ['permitAll'],
		        '/**':                            ['permitAll']
		    ]

		    providerNames = [
		        'facebookAuthProvider',
		        'clientCredentialsAuthenticationProvider',
		        'daoAuthenticationProvider',
		        'anonymousAuthenticationProvider',
		        'rememberMeAuthenticationProvider'
		    ]
		    oauthProvider {
		        clientLookup.className = 'user.Client'
		        authorizationCodeLookup.className = 'user.AuthorizationCode'
		        accessTokenLookup.className = 'user.AccessToken'
		        refreshTokenLookup.className = 'user.RefreshToken'
		        authorization.requireScope = false
		    }
		}
	    }
	}

Have you an idea about this problem ?

Thanks

**Comment by bluesliverx** [comment]
Possible duplicates of #65 and #80.

**Comment by dynamind** [comment]
Do you have the same problem in `:spring-security-oauth2-provider:2.0-RC3`?

**Comment by moniman** [comment]
yes.
but when I remove oauth plugin, everything works.

**Comment by vbaarda** [comment]
If it works in RC2 and not in RC3, it might be the same issue as #78.

Try adding org.springframework.security to your debug logging and look for something like this in your log:

2015-03-26T14:26:11.318-0600	http-bio-8080-exec-3	DEBUG	org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter	0		Clearing security context.

**Comment by moniman** [comment]
my logs : 



	2015-03-27 21:15:14 authentication.RequestHolderAuthenticationFilter Request is to process authentication
	2015-03-27 21:15:14 hibernate.SQL select this_.id as id1_18_0_, this_.version as version2_18_0_, this_.access_token_validity_seconds as access_t3_18_0_, this_.client_id as client_i4_18_0_, this_.client_secret as client_s5_18_0_, this_.refresh_token_validity_seconds as refresh_6_18_0_ from client this_ where (this_.client_id=?) limit ?
	2015-03-27 21:15:14 hibernate.SQL select this_.id as id1_49_0_, this_.version as version2_49_0_, this_.account_expired as account_3_49_0_, this_.account_locked as account_4_49_0_, this_.date_created as date_cre5_49_0_, this_.email as email6_49_0_, this_.enabled as enabled7_49_0_, this_.last_updated as last_upd8_49_0_, this_.`password` as password9_49_0_, this_.password_expired as passwor10_49_0_, this_.username as usernam11_49_0_ from user this_ where (this_.username=? or this_.email=?) limit ?
	2015-03-27 21:15:14 hibernate.SQL select userfacebo0_.id as id1_50_0_, userfacebo0_.version as version2_50_0_, userfacebo0_.access_token as access_t3_50_0_, userfacebo0_.access_token_expires as access_t4_50_0_, userfacebo0_.uid as uid5_50_0_, userfacebo0_.user_id as user_id6_50_0_ from user_facebook userfacebo0_ where userfacebo0_.user_id=?
	2015-03-27 21:15:14 hibernate.SQL select profile0_.id as id1_42_0_, profile0_.version as version2_42_0_, profile0_.about_me as about_me3_42_0_, profile0_.birth as birth4_42_0_, profile0_.city as city5_42_0_, profile0_.country as country6_42_0_, profile0_.date_created as date_cre7_42_0_, profile0_.first_name as first_na8_42_0_, profile0_.gender as gender9_42_0_, profile0_.last_name as last_na10_42_0_, profile0_.last_updated as last_up11_42_0_, profile0_.phone as phone12_42_0_, profile0_.picture as picture13_42_0_, profile0_.picture_path as picture14_42_0_, profile0_.picture_thumbnail as picture15_42_0_, profile0_.picture_thumbnail_mini as picture16_42_0_, profile0_.slogan as slogan17_42_0_, profile0_.state as state18_42_0_, profile0_.street as street19_42_0_, profile0_.stripe_customer_id as stripe_20_42_0_, profile0_.tradesman_id as tradesm21_42_0_, profile0_.user_id as user_id22_42_0_, profile0_.zip as zip23_42_0_ from profile profile0_ where profile0_.user_id=?
	2015-03-27 21:15:14 hibernate.SQL select this_.role_id as role_id1_51_0_, this_.user_id as user_id2_51_0_ from user_role this_ where this_.user_id=?
	2015-03-27 21:15:14 hibernate.SQL select role0_.id as id1_46_0_, role0_.version as version2_46_0_, role0_.authority as authorit3_46_0_ from role role0_ where role0_.id in (?, ?, ?, ?)
	2015-03-27 21:15:14 hibernate.SQL select tradesman0_.id as id1_48_0_, tradesman0_.version as version2_48_0_ from tradesman tradesman0_ where tradesman0_.id=?
	2015-03-27 21:15:14 hibernate.SQL select profile0_.id as id1_42_0_, profile0_.version as version2_42_0_, profile0_.about_me as about_me3_42_0_, profile0_.birth as birth4_42_0_, profile0_.city as city5_42_0_, profile0_.country as country6_42_0_, profile0_.date_created as date_cre7_42_0_, profile0_.first_name as first_na8_42_0_, profile0_.gender as gender9_42_0_, profile0_.last_name as last_na10_42_0_, profile0_.last_updated as last_up11_42_0_, profile0_.phone as phone12_42_0_, profile0_.picture as picture13_42_0_, profile0_.picture_path as picture14_42_0_, profile0_.picture_thumbnail as picture15_42_0_, profile0_.picture_thumbnail_mini as picture16_42_0_, profile0_.slogan as slogan17_42_0_, profile0_.state as state18_42_0_, profile0_.street as street19_42_0_, profile0_.stripe_customer_id as stripe_20_42_0_, profile0_.tradesman_id as tradesm21_42_0_, profile0_.user_id as user_id22_42_0_, profile0_.zip as zip23_42_0_ from profile profile0_ where profile0_.tradesman_id=?
	2015-03-27 21:15:14 hibernate.SQL select merchants0_.owner_id as owner_i18_48_1_, merchants0_.id as id1_31_1_, merchants0_.id as id1_31_0_, merchants0_.version as version2_31_0_, merchants0_.city as city3_31_0_, merchants0_.close_from as close_fr4_31_0_, merchants0_.close_to as close_to5_31_0_, merchants0_.complement as compleme6_31_0_, merchants0_.country as country7_31_0_, merchants0_.date_created as date_cre8_31_0_, merchants0_.description as descript9_31_0_, merchants0_.email as email10_31_0_, merchants0_.enabled as enabled11_31_0_, merchants0_.facebook as faceboo12_31_0_, merchants0_.last_subscription_id as last_su13_31_0_, merchants0_.last_updated as last_up14_31_0_, merchants0_.location as locatio15_31_0_, merchants0_.name as name16_31_0_, merchants0_.nb_rate as nb_rate17_31_0_, merchants0_.owner_id as owner_i18_31_0_, merchants0_.owner_name as owner_n19_31_0_, merchants0_.phone as phone20_31_0_, merchants0_.picture_principal as picture21_31_0_, merchants0_.picture_principal_original as picture22_31_0_, merchants0_.rate as rate23_31_0_, merchants0_.slug as slug24_31_0_, merchants0_.state as state25_31_0_, merchants0_.street as street26_31_0_, merchants0_.twitter as twitter27_31_0_, merchants0_.validated as validat28_31_0_, merchants0_.website as website29_31_0_, merchants0_.zip as zip30_31_0_ from merchant merchants0_ where merchants0_.owner_id=?
	2015-03-27 21:15:14 authentication.RequestHolderAuthenticationFilter Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@cb70c344: Principal: user.MyUserDetails@62dd304: Username: moni; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_MERCHANT,ROLE_SWITCH_USER,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffd148a: RemoteIpAddress: 127.0.0.1; SessionId: D48F05E54EDBF8305EEC7D8B43E6B1B7; Granted Authorities: ROLE_MERCHANT, ROLE_USER, ROLE_ADMIN, ROLE_SWITCH_USER
	2015-03-27 21:15:14 filter.GrailsAnonymousAuthenticationFilter Populated SecurityContextHolder with anonymous token: 'grails.plugin.springsecurity.authentication.GrailsAnonymousAuthenticationToken@dc64d76: Principal: org.springframework.security.core.userdetails.User@dc730200: Username: __grails.anonymous.user__; Password: [PROTECTED]; Enabled: false; AccountNonExpired: false; credentialsNonExpired: false; AccountNonLocked: false; Granted Authorities: ROLE_ANONYMOUS; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@2eb76: RemoteIpAddress: 127.0.0.1; SessionId: 10626B83AD88F1A400ADDF6530205C2C; Granted Authorities: ROLE_ANONYMOUS'
	2015-03-27 21:15:15 filter.GrailsAnonymousAuthenticationFilter Populated SecurityContextHolder with anonymous token: 'grails.plugin.springsecurity.authentication.GrailsAnonymousAuthenticationToken@dc64d76: Principal: org.springframework.security.core.userdetails.User@dc730200: Username: __grails.anonymous.user__; Password: [PROTECTED]; Enabled: false; AccountNonExpired: false; credentialsNonExpired: false; AccountNonLocked: false; Granted Authorities: ROLE_ANONYMOUS; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@2eb76: RemoteIpAddress: 127.0.0.1; SessionId: 10626B83AD88F1A400ADDF6530205C2C; Granted Authorities: ROLE_ANONYMOUS'
	2015-03-27 21:15:17 filter.GrailsAnonymousAuthenticationFilter Populated SecurityContextHolder with anonymous token: 'grails.plugin.springsecurity.authentication.GrailsAnonymousAuthenticationToken@dc64d76: Principal: org.springframework.security.core.userdetails.User@dc730200: Username: __grails.anonymous.user__; Password: [PROTECTED]; Enabled: false; AccountNonExpired: false; credentialsNonExpired: false; AccountNonLocked: false; Granted Authorities: ROLE_ANONYMOUS; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@2eb76: RemoteIpAddress: 127.0.0.1; SessionId: 10626B83AD88F1A400ADDF6530205C2C; Granted Authorities: ROLE_ANONYMOUS'

**Comment by bobby-vandiver** [comment]
Could you provide your filter chain configuration and more logging before what you posted? Specifically, the logs pertaining to the filter chain for the problematic request would be most helpful.

**Comment by moniman** [comment]
2015-03-27 23:24:12 filter.DebugFilter 
	************************************************************
	Request received for '/j_spring_security_check':
	org.apache.catalina.connector.RequestFacade@5192a91c
	servletPath:/j_spring_security_check
	pathInfo:null
	Security filter chain: [
	  SecurityContextPersistenceFilter
	  StatelessSecurityContextPersistenceFilter
	  MutableLogoutFilter
	  OAuth2AuthenticationProcessingFilter
	  FacebookAuthRedirectFilter
	  RequestHolderAuthenticationFilter
	  ClientCredentialsTokenEndpointFilter
	  SecurityContextHolderAwareRequestFilter
	  GrailsRememberMeAuthenticationFilter
	  GrailsAnonymousAuthenticationFilter
	  ExceptionTranslationFilter
	  FilterSecurityInterceptor
	  SwitchUserFilter
	]
	************************************************************
	2015-03-27 23:24:12 hibernate.SQL select this_.id as id1_18_0_, this_.version as version2_18_0_, this_.access_token_validity_seconds as access_t3_18_0_, this_.client_id as client_i4_18_0_, this_.client_secret as client_s5_18_0_, this_.refresh_token_validity_seconds as refresh_6_18_0_ from client this_ where (this_.client_id=?) limit ?
	2015-03-27 23:24:12 hibernate.SQL select this_.id as id1_49_0_, this_.version as version2_49_0_, this_.account_expired as account_3_49_0_, this_.account_locked as account_4_49_0_, this_.date_created as date_cre5_49_0_, this_.email as email6_49_0_, this_.enabled as enabled7_49_0_, this_.last_updated as last_upd8_49_0_, this_.`password` as password9_49_0_, this_.password_expired as passwor10_49_0_, this_.username as usernam11_49_0_ from user this_ where (this_.username=? or this_.email=?) limit ?
	2015-03-27 23:24:12 hibernate.SQL select userfacebo0_.id as id1_50_0_, userfacebo0_.version as version2_50_0_, userfacebo0_.access_token as access_t3_50_0_, userfacebo0_.access_token_expires as access_t4_50_0_, userfacebo0_.uid as uid5_50_0_, userfacebo0_.user_id as user_id6_50_0_ from user_facebook userfacebo0_ where userfacebo0_.user_id=?
	2015-03-27 23:24:12 hibernate.SQL select profile0_.id as id1_42_0_, profile0_.version as version2_42_0_, profile0_.about_me as about_me3_42_0_, profile0_.birth as birth4_42_0_, profile0_.city as city5_42_0_, profile0_.country as country6_42_0_, profile0_.date_created as date_cre7_42_0_, profile0_.first_name as first_na8_42_0_, profile0_.gender as gender9_42_0_, profile0_.last_name as last_na10_42_0_, profile0_.last_updated as last_up11_42_0_, profile0_.phone as phone12_42_0_, profile0_.picture as picture13_42_0_, profile0_.picture_path as picture14_42_0_, profile0_.picture_thumbnail as picture15_42_0_, profile0_.picture_thumbnail_mini as picture16_42_0_, profile0_.slogan as slogan17_42_0_, profile0_.state as state18_42_0_, profile0_.street as street19_42_0_, profile0_.stripe_customer_id as stripe_20_42_0_, profile0_.tradesman_id as tradesm21_42_0_, profile0_.user_id as user_id22_42_0_, profile0_.zip as zip23_42_0_ from profile profile0_ where profile0_.user_id=?
	2015-03-27 23:24:12 hibernate.SQL select this_.role_id as role_id1_51_0_, this_.user_id as user_id2_51_0_ from user_role this_ where this_.user_id=?
	2015-03-27 23:24:12 hibernate.SQL select role0_.id as id1_46_0_, role0_.version as version2_46_0_, role0_.authority as authorit3_46_0_ from role role0_ where role0_.id in (?, ?, ?, ?)
	2015-03-27 23:24:12 hibernate.SQL select tradesman0_.id as id1_48_0_, tradesman0_.version as version2_48_0_ from tradesman tradesman0_ where tradesman0_.id=?
	2015-03-27 23:24:12 hibernate.SQL select profile0_.id as id1_42_0_, profile0_.version as version2_42_0_, profile0_.about_me as about_me3_42_0_, profile0_.birth as birth4_42_0_, profile0_.city as city5_42_0_, profile0_.country as country6_42_0_, profile0_.date_created as date_cre7_42_0_, profile0_.first_name as first_na8_42_0_, profile0_.gender as gender9_42_0_, profile0_.last_name as last_na10_42_0_, profile0_.last_updated as last_up11_42_0_, profile0_.phone as phone12_42_0_, profile0_.picture as picture13_42_0_, profile0_.picture_path as picture14_42_0_, profile0_.picture_thumbnail as picture15_42_0_, profile0_.picture_thumbnail_mini as picture16_42_0_, profile0_.slogan as slogan17_42_0_, profile0_.state as state18_42_0_, profile0_.street as street19_42_0_, profile0_.stripe_customer_id as stripe_20_42_0_, profile0_.tradesman_id as tradesm21_42_0_, profile0_.user_id as user_id22_42_0_, profile0_.zip as zip23_42_0_ from profile profile0_ where profile0_.tradesman_id=?
	2015-03-27 23:24:12 hibernate.SQL select settings0_.owner_id as owner_i18_48_1_, settings0_.id as id1_31_1_, settings0_.id as id1_31_0_, settings0_.version as version2_31_0_, settings0_.city as city3_31_0_, settings0_.close_from as close_fr4_31_0_, settings0_.close_to as close_to5_31_0_, settings0_.complement as compleme6_31_0_, settings0_.country as country7_31_0_, settings0_.date_created as date_cre8_31_0_, settings0_.description as descript9_31_0_, settings0_.email as email10_31_0_, settings0_.enabled as enabled11_31_0_, settings0_.facebook as faceboo12_31_0_, settings0_.last_subscription_id as last_su13_31_0_, settings0_.last_updated as last_up14_31_0_, settings0_.location as locatio15_31_0_, settings0_.name as name16_31_0_, settings0_.nb_rate as nb_rate17_31_0_, settings0_.owner_id as owner_i18_31_0_, settings0_.owner_name as owner_n19_31_0_, settings0_.phone as phone20_31_0_, settings0_.picture_principal as picture21_31_0_, settings0_.picture_principal_original as picture22_31_0_, settings0_.rate as rate23_31_0_, settings0_.slug as slug24_31_0_, settings0_.state as state25_31_0_, settings0_.street as street26_31_0_, settings0_.twitter as twitter27_31_0_, settings0_.validated as validat28_31_0_, settings0_.website as website29_31_0_, settings0_.zip as zip30_31_0_ from merchant settings0_ where settings0_.owner_id=?
	2015-03-27 23:24:13 filter.DebugFilter 
	************************************************************
	New HTTP session created: 92CA5AFFE3812BCD5F6CC857EA638500
	Call stack: 
		at grails.plugin.springsecurity.web.filter.DebugFilter.log(DebugFilter.java:145)
		at grails.plugin.springsecurity.web.filter.DebugFilter$1.getSession(DebugFilter.java:89)
		at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:240)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
		at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:60)
		at groovy.lang.MetaBeanProperty$getProperty.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
		at groovy.lang.MetaBeanProperty$getProperty.call(Unknown Source)
		at org.codehaus.groovy.grails.plugins.web.ServletsGrailsPluginSupport$_enhanceServletApi_closure1.doCall(ServletsGrailsPluginSupport.groovy:38)
		at sun.reflect.GeneratedMethodAccessor301.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:81)
		at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1161)
		at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
		at org.codehaus.groovy.runtime.callsite.PojoMetaClassGetPropertySite.getProperty(PojoMetaClassGetPropertySite.java:33)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:293)
		at user.MyAuthSuccessHandler.determineTargetUrl(MyAuthSuccessHandler.groovy:35)
		at org.springframework.security.web.authentication.AbstractAuthenticationTargetUrlRequestHandler.handle(AbstractAuthenticationTargetUrlRequestHandler.java:69)
		at user.MyAuthSuccessHandler.handle(MyAuthSuccessHandler.groovy)
		at org.springframework.security.web.authentication.SimpleUrlAuthenticationSuccessHandler.onAuthenticationSuccess(SimpleUrlAuthenticationSuccessHandler.java:42)
		at org.springframework.security.web.authentication.SavedRequestAwareAuthenticationSuccessHandler.onAuthenticationSuccess(SavedRequestAwareAuthenticationSuccessHandler.java:63)
		at user.MyAuthSuccessHandler.super$4$onAuthenticationSuccess(MyAuthSuccessHandler.groovy)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
		at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1121)
		at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
		at user.MyAuthSuccessHandler.onAuthenticationSuccess(MyAuthSuccessHandler.groovy:28)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilter.java:331)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilter.java:298)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:235)
		at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
		at com.the6hours.grails.springsecurity.facebook.FacebookAuthRedirectFilter.doFilter(FacebookAuthRedirectFilter.groovy:46)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
		at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:160)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
		at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:65)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
		at grails.plugin.springsecurity.web.filter.DebugFilter.invokeWithWrappedRequest(DebugFilter.java:102)
		at grails.plugin.springsecurity.web.filter.DebugFilter.doFilter(DebugFilter.java:69)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:69)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
		at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
		at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
		at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:745)
	************************************************************
	2015-03-27 23:24:13 filter.DebugFilter 
	************************************************************
	Request received for '/settings':
	org.apache.catalina.connector.RequestFacade@5192a91c
	servletPath:/settings
	pathInfo:null
	Security filter chain: [
	  SecurityContextPersistenceFilter
	  StatelessSecurityContextPersistenceFilter
	  MutableLogoutFilter
	  OAuth2AuthenticationProcessingFilter
	  FacebookAuthRedirectFilter
	  RequestHolderAuthenticationFilter
	  ClientCredentialsTokenEndpointFilter
	  SecurityContextHolderAwareRequestFilter
	  GrailsRememberMeAuthenticationFilter
	  GrailsAnonymousAuthenticationFilter
	  ExceptionTranslationFilter
	  FilterSecurityInterceptor
	  SwitchUserFilter
	]
	************************************************************
	2015-03-27 23:24:13 filter.DebugFilter 
	************************************************************
	Request received for '/login':
	org.apache.catalina.connector.RequestFacade@5192a91c
	servletPath:/login
	pathInfo:null
	Security filter chain: [
	  SecurityContextPersistenceFilter
	  StatelessSecurityContextPersistenceFilter
	  MutableLogoutFilter
	  OAuth2AuthenticationProcessingFilter
	  FacebookAuthRedirectFilter
	  RequestHolderAuthenticationFilter
	  ClientCredentialsTokenEndpointFilter
	  SecurityContextHolderAwareRequestFilter
	  GrailsRememberMeAuthenticationFilter
	  GrailsAnonymousAuthenticationFilter
	  ExceptionTranslationFilter
	  FilterSecurityInterceptor
	  SwitchUserFilter
	]
	************************************************************
	2015-03-27 23:24:17 filter.DebugFilter 
	************************************************************
	Request received for '/login':
	org.apache.catalina.connector.RequestFacade@4965621a
	servletPath:/login
	pathInfo:null
	Security filter chain: [
	  SecurityContextPersistenceFilter
	  StatelessSecurityContextPersistenceFilter
	  MutableLogoutFilter
	  OAuth2AuthenticationProcessingFilter
	  FacebookAuthRedirectFilter
	  RequestHolderAuthenticationFilter
	  ClientCredentialsTokenEndpointFilter
	  SecurityContextHolderAwareRequestFilter
	  GrailsRememberMeAuthenticationFilter
	  GrailsAnonymousAuthenticationFilter
	  ExceptionTranslationFilter
	  FilterSecurityInterceptor
	  SwitchUserFilter
	]
	************************************************************

**Comment by bobby-vandiver** [comment]
@moniman  Can you post your `grails.plugin.springsecurity.filterChain.chainMap` configuration? Your original post and the logs suggest that the filter chain has been configured properly. See the documentation for [filter chain configuration](http://bluesliverx.github.io/grails-spring-security-oauth2-provider/guide/configuration.html#filterChainConfig)

**Comment by dynamind** [comment]
Your log file shows that `oauth2ProviderFilter` (class name `OAuth2AuthenticationProcessingFilter `) is included in the filter chain of a non-oauth root, e.g. `'/**'`. At least, that's the mapping paths such as `/settings` and `/login` respond to. Make sure it is removed. For example, in your `Config.groovy`, notice the `-oauth2ProviderFilter` in the `/**` mapping:

    grails.plugin.springsecurity.filterChain.chainMap = [
        '/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-basicAuthenticationFilter,-exceptionTranslationFilter',
        '/v1/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-basicAuthenticationFilter,-oauth2BasicAuthenticationFilter,-exceptionTranslationFilter',
        '/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-oauth2BasicAuthenticationFilter,-oauth2ExceptionTranslationFilter'
    ]

**Comment by moniman** [comment]
Hi, 

I don't have chainMap in my config and never use it before
bobby-vandiver and dynamind, It's works by adding chainMap ! 
Thank you

**Comment by bobby-vandiver** [comment]
Sounds like this is resolved. Closing.
